R CMD INSTALL --build \
/tmp/packages/gtools_3.9.4.tar.gz \
/tmp/packages/bitops_1.0-7.tar.gz \
/tmp/packages/GenomeInfoDbData_1.2.7.tar.gz \
/tmp/packages/zlibbioc_1.40.0.tar.gz \
/tmp/packages/BiocGenerics_0.40.0.tar.gz \
/tmp/packages/BiocVersion_3.14.0.tar.gz \
/tmp/packages/RCurl_1.98-1.9.tar.gz \
/tmp/packages/S4Vectors_0.32.4.tar.gz \
/tmp/packages/IRanges_2.28.0.tar.gz \
/tmp/packages/GenomeInfoDb_1.30.1.tar.gz \
/tmp/packages/XVector_0.34.0.tar.gz \
/tmp/packages/GenomicRanges_1.46.1.tar.gz \
/tmp/packages/cli_3.6.0.tar.gz \
/tmp/packages/glue_1.6.2.tar.gz \
/tmp/packages/colorspace_2.0-3.tar.gz \
/tmp/packages/farver_2.1.1.tar.gz \
/tmp/packages/labeling_0.4.2.tar.gz \
/tmp/packages/R6_2.5.1.tar.gz \
/tmp/packages/rlang_1.0.6.tar.gz \
/tmp/packages/viridisLite_0.4.1.tar.gz \
/tmp/packages/RColorBrewer_1.1-3.tar.gz \
/tmp/packages/gtable_0.3.1.tar.gz \
/tmp/packages/lifecycle_1.0.3.tar.gz \
/tmp/packages/munsell_0.5.0.tar.gz \
/tmp/packages/scales_1.2.1.tar.gz \
/tmp/packages/pheatmap_1.0.12.tar.gz \
/tmp/packages/fs_1.5.2.tar.gz \
/tmp/packages/rappdirs_0.3.3.tar.gz \
/tmp/packages/sys_3.4.1.tar.gz \
/tmp/packages/stringi_1.7.8.tar.gz \
/tmp/packages/proxy_0.4-27.tar.gz \
/tmp/packages/evaluate_0.19.tar.gz \
/tmp/packages/xfun_0.36.tar.gz \
/tmp/packages/wk_0.7.1.tar.gz \
/tmp/packages/utf8_1.2.2.tar.gz \
/tmp/packages/curl_4.3.3.tar.gz \
/tmp/packages/mime_0.12.tar.gz \
/tmp/packages/fastmap_1.1.0.tar.gz \
/tmp/packages/ellipsis_0.3.2.tar.gz \
/tmp/packages/yaml_2.3.6.tar.gz \
/tmp/packages/cpp11_0.4.3.tar.gz \
/tmp/packages/polyclip_1.10-4.tar.gz \
/tmp/packages/permute_0.9-7.tar.gz \
/tmp/packages/DBI_1.1.3.tar.gz \
/tmp/packages/Rcpp_1.0.9.tar.gz \
/tmp/packages/isoband_0.2.7.tar.gz \
/tmp/packages/vctrs_0.5.1.tar.gz \
/tmp/packages/withr_2.5.0.tar.gz \
/tmp/packages/generics_0.1.3.tar.gz \
/tmp/packages/fansi_1.0.3.tar.gz \
/tmp/packages/pkgconfig_2.0.3.tar.gz \
/tmp/packages/jsonlite_1.8.4.tar.gz \
/tmp/packages/digest_0.6.31.tar.gz \
/tmp/packages/base64enc_0.1-3.tar.gz \
/tmp/packages/lazyeval_0.2.2.tar.gz \
/tmp/packages/data.table_1.14.6.tar.gz \
/tmp/packages/magrittr_2.0.3.tar.gz \
/tmp/packages/yulab.utils_0.0.6.tar.gz \
/tmp/packages/cachem_1.0.6.tar.gz \
/tmp/packages/askpass_1.1.tar.gz \
/tmp/packages/highr_0.10.tar.gz \
/tmp/packages/stringr_1.5.0.tar.gz \
/tmp/packages/tinytex_0.43.tar.gz \
/tmp/packages/e1071_1.7-12.tar.gz \
/tmp/packages/later_1.3.0.tar.gz \
/tmp/packages/tweenr_2.0.2.tar.gz \
/tmp/packages/systemfonts_1.0.4.tar.gz \
/tmp/packages/RcppEigen_0.3.3.9.3.tar.gz \
/tmp/packages/s2_1.1.1.tar.gz \
/tmp/packages/units_0.8-1.tar.gz \
/tmp/packages/tidyselect_1.2.0.tar.gz \
/tmp/packages/pillar_1.8.1.tar.gz \
/tmp/packages/htmltools_0.5.4.tar.gz \
/tmp/packages/vegan_2.6-4.tar.gz \
/tmp/packages/purrr_1.0.0.tar.gz \
/tmp/packages/sass_0.4.4.tar.gz \
/tmp/packages/memoise_2.0.1.tar.gz \
/tmp/packages/jquerylib_0.1.4.tar.gz \
/tmp/packages/openssl_2.0.5.tar.gz \
/tmp/packages/knitr_1.41.tar.gz \
/tmp/packages/classInt_0.4-8.tar.gz \
/tmp/packages/crosstalk_1.2.0.tar.gz \
/tmp/packages/promises_1.2.0.1.tar.gz \
/tmp/packages/tibble_3.1.8.tar.gz \
/tmp/packages/bslib_0.4.2.tar.gz \
/tmp/packages/httr_1.4.4.tar.gz \
/tmp/packages/sf_1.0-9.tar.gz \
/tmp/packages/ggplot2_3.4.0.tar.gz \
/tmp/packages/dplyr_1.0.10.tar.gz \
/tmp/packages/rmarkdown_2.19.tar.gz \
/tmp/packages/tidyr_1.2.1.tar.gz \
/tmp/packages/ggforce_0.4.1.tar.gz \
/tmp/packages/htmlwidgets_1.6.1.tar.gz \
/tmp/packages/RVenn_1.1.0.tar.gz \
/tmp/packages/plotly_4.10.1.tar.gz \
/tmp/packages/ggVennDiagram_1.2.2.tar.gz \
/tmp/packages/sm_2.2-5.7.1.tar.gz \
/tmp/packages/zoo_1.8-11.tar.gz \
/tmp/packages/vioplot_0.4.0.tar.gz \
/tmp/packages/argparser_0.7.1.tar.gz \
/tmp/packages/GenSA_1.1.7.tar.gz \
/tmp/packages/polylabelr_0.2.0.tar.gz \
/tmp/packages/RcppArmadillo_0.11.4.2.1.tar.gz \
/tmp/packages/eulerr_7.0.0.tar.gz \
